### ISSUE TITLE
Release Model

### ISSUE THREAD

**Issue by Quest2GM** [rakeshshrestha31/map_prediction_enhanced_exploration#7]
Hi @rakeshshrestha31,

Thanks for releasing your code for this. Is it possible to release your pre-trained model? It would really help a lot of people who are struggling to make this repository work, and would save everyone a lot of time.

Best regards,
Siddarth

**Comment by rakeshshrestha31** [comment]
Hi Siddarth @Quest2GM,

Thank you for your interest in this project. Unfortunately I lost the pre-trained model due to hard drive failure a few years ago and I cannot find a backup of it. Feel free to create other issues that you are facing and I'll try to help as much as I can.

Best,
Rakesh
