### ISSUE TITLE
Reproducing the Results

### ISSUE THREAD

**Issue by Quest2GM** [rakeshshrestha31/map_prediction_enhanced_exploration#8]
Hi @rakeshshrestha31,

Thanks for responding to my original question before.

It would be helpful to get some guidance as to how to reproduce this code. I am currently working in ROS Melodic and had a bunch of issues with `catkin_make`. However, I was able to use this implementation to solve it: https://github.com/wecacuee/map_prediction_enhanced_exploration. In other words, I got all of the setup stuff done as the instructions say. But when I try to run `rosrun stage_frontier_datagen kth_stage_node _dataset_dir:=<kth_dataset_dir> _data_record_dir:=<generated_dataset_dir>`, this results in:

[ INFO] [1663459112.222657887]: planner failed
[ INFO] [1663459112.222663440]: Received new plan
[ INFO] [1663459112.224257456]: running planner...
[ WARN] [1663459112.247933702]: [hector_exploration_planner] exploration: No valid frontiers found!

Maybe I am missing an important step but I am not sure what I need to run and in what order.
1. A more detailed instruction list on how to exactly run the planner, how to clean the dataset, how to generate the partial map dataset, and how to run it with the simulator would be helpful.
2. Addressing the issues mentioned in #2 would be nice, so that we know that this repository is still following the publication.

I know this may potentially be a lot, but it would be great if you can address at least a few of these!

Thanks,
Quest2GM

**Comment by rakeshshrestha31** [comment]
Hi Quest2GM,

I'm really sorry for the problems with rerunning the code. At the time I thought the readme instructions would be enough. Do you have a docker image or a dockerfile so that I can reproduce your environment and check what's causing the problem?

Best,
Rakesh

**Comment by Quest2GM** [comment]
Hi @rakeshshrestha31,

The way you can reproduce mine is by `docker pull osrf/ros:melodic-desktop-full`. Then clone this repository: https://github.com/wecacuee/map_prediction_enhanced_exploration. Then follow your readme to install and then catkin_make.

Let me know if you come across issues.
Thanks

**Comment by Quest2GM** [comment]
So I found out that my issue was that I needed to run the simulator first with `roslaunch stage_frontier_datagen kth_datagen.launch` and `roslaunch stage_frontier_datagen kth_datagen_standalone.launch` first before running `rosrun stage_frontier_datagen kth_stage_node _dataset_dir:=<kth_dataset_dir> _data_record_dir:=<generated_dataset_dir>`. Might be useful to include this in the readme for future users.
